### ISSUE TITLE
Hybrid coefficients calculations

### ISSUE THREAD

**Issue by EnnnG** [oskarholmberg/wow-downranking#24]
Hello,

First, thank you for your work, it is very interesting to play with numbers like that. In my attempt to understand the calculations I checked your code and found out something weird. 

You have a function in the calculations.js sheet called getHybridCoeficients but it seems like you use pre-calculated coefficients (spelldata.directCoeff and spelldata.overTimeCoeff) in your calculations. I tried to compute these coefficients myself based on your guide, and the getHybridCoeficients function, and my results are different from your pre-calculated ones.

Let’s see for the druid spell regrowth :

baseCastTime = 2 > 1.5 so castTime = 2
tickDuration = 21 > 15 so duration 15

overTimePortion = (duration / 15) / ((duration / 15) + (castTime / 3.5)) = 1 / (1 + (2 / 3.5)) = 0.636
overTimeCoef = (duration / 15) * overTimePortion = 1 * overTimePortion = 0.636

directPortion =  1 - overTimePortion = 0.364
directCoef = (castTime / 3.5) * directPortion = (2 / 3.5) * 0.364 = 0.208

In the regrowth data sheet these values are set to : 
directCoeff = 0.325
overTimeCoeff = 0.513

You can see quite a difference between our results but maybe I misunderstood something in the calculations.

Regards,

**Comment by oskarwiskman** [comment]
Thanks for taking your time to review my work, and I'm glad you appreciate what I'm trying to do.

So yes, in the guide there is an example of how to calculate hybrid spells, the problem is though that many spells diverge from the "rules" and have specific and unique coefficients. Regrowth is one of them, I don't know why this is done, but I assume it's balancing issues Blizzard has had where they have later manually tweaked some spells.

The sources for hardcoded values of Direct: 0.325 and OverTime: 0.513 came from both the TheoryCraft addon source code, and a druid downranking calculation sheet I found. Sadly I cannot find that sheet anymore and can't provide the link. But since both of these sources were held in high regard, and had the exact same hard coded values. I decided to go with those.

Since Regrowth is the only Hybrid spell available in the tool, the function is quite useless as of now, but since I had already made the logic for it, I decided to leave it in the source code in case I wanted to add any other hybrid spells.

I have added a disclaimer in the guide saying this to avoid further confusion.

Again, thanks for showing such an interest. and if you find other sources on how regrowth works please let me know!
