### ISSUE TITLE
Blessing of Light bonuses for Holy Light; Healing Light talent calculation

### ISSUE THREAD

**Issue by Blaticus** [oskarholmberg/wow-downranking#28]
Hello,

I have been working on a project that parallels your work on Paladin downranking, and our results mostly agree. However I saw a couple of discrepancies:

It seems the bonus to Holy Light ranks 1, 2, and 3 healing from Blessing of Light isn't being calculated correctly on the website. The reported average healing values seem to be too high.

Additionally, during my work I found that the Paladin talent for +12% healing on Holy Light and Flash of Light appears to actually only apply to the base healing for the spells, not as a final modifier after SC calculations. (The spell tool-tips for the spells display updated numbers with talent points in the talent.)

I can document some experimental data from in-game trials if desired.

**Comment by oskarwiskman** [comment]
Hello,

Thanks for taking the time to bring me some feedback. What exactly are you seeing wrong with the Blessing of Light? Since my guide is for downranking and this is primarily done at lvl 60 I have only included rank 3 of BoL. In addition to this I treat the extra healing to FoL and HL as 1:1 healing, and not as "regular" healing power. So just a flat increase. They are however taken into account when calculating extra average healing based on crits. 

The Healing Light talent is not applied to the extra healing gained from gear. And only increases the base healing of each spell. 

What numbers have you used in the tool, and what output are you getting? Because I am doing the calculations as you describe in your post.

**Comment by oskarwiskman** [comment]
Closing this due to no response.
