### ISSUE TITLE
Paladin Flash Heal Base Values

### ISSUE THREAD

**Issue by TristramGoose** [oskarholmberg/wow-downranking#30]
Hello, I think the paladin heal values for flash of light are off in the flash of light json file. 
I ran a test on my lv 60 human holy paladin by removing all my gear and unlearning all my talents then looking at the tooltips. 
For some reason the online databases seem to all be fairly inconsistent on how much these spells heal. 

Rank 1: 67-77
Rank 2: 102-117
Rank 3: 153-171
Rank 4: 206-231
Rank 5: 278-310
Rank 6: 348-389

Here is a sample screenshot. If you want all my screenshots of the values let me know. 
![Rank1Flash](https://user-images.githubusercontent.com/30111689/88557651-7d584f80-cff8-11ea-867d-d702df56a149.png)

**Comment by oskarwiskman** [comment]
Hello! Thanks for your input. There is a factor in each spell (affected by character level) that keeps increasing the power of ranks up until the level before you can train the next rank of that spell. 

So for a lvl 20 paladin that just learned Flash of Light rank 1, the interval would be 62-72 healing, but for any paladin level 25 or higher, the same Rank 1 FoL will heal for 67-77. To my knowledge this effect was unknown before the release of Classic, since I have not seen any private server use this, nor it being referenced in other forums. Classic wowhead actually updated their spells with sliders a month or so in to classic, so you can see powers of the spells for each level.

Since this tool is mean to be used at 60 I am considering to just change all values to match the 60 values, since I don't have the infrastructure atm, so save multiple values for each spell rank. However the perfectionist inside me wants to make this depend on your level too, which is why I have not gotten around to do it. I will try to get a quick patch out, that just assumes all users are lvl 60.

Thanks for your feedback!

**Comment by oskarwiskman** [comment]
This has been fixed by [e056425](https://github.com/oskarholmberg/wow-downranking/commit/e056425b858c3b129c631aa6ff0d7793f1d84d56)
